language: python
python:
  - "3.6"
before_script:
  - pip install -r requirements.txt
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter env
  - ./cc-test-reporter before-build
script:
  - coverage run test/solutions.py
  - coverage report
  - coverage xml
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
  - coveralls
